import {
  ArrowRight,
  ArrowUp,
  Award,
  CheckCircle,
  Facebook,
  Github,
  Heart,
  Linkedin,
  Mail,
  MapPin,
  Menu,
  MessageCircle,
  Phone,
  Rocket,
  Send,
  Sparkles,
  Star,
  Target,
  TrendingUp,
  Twitter,
  Users,
  X,
  Zap,
  type LucideIcon,
} from 'lucide-react'

const ICON_MAP: Record<string, LucideIcon> = {
  arrowRight: ArrowRight,
  arrowUp: ArrowUp,
  award: Award,
  Award,
  checkCircle: CheckCircle,
  facebook: Facebook,
  github: Github,
  heart: Heart,
  linkedin: Linkedin,
  mail: Mail,
  Mail,
  mapPin: MapPin,
  MapPin,
  menu: Menu,
  messageCircle: MessageCircle,
  phone: Phone,
  Phone,
  rocket: Rocket,
  send: Send,
  sparkles: Sparkles,
  star: Star,
  target: Target,
  trending: TrendingUp,
  trendingUp: TrendingUp,
  twitter: Twitter,
  users: Users,
  Users,
  x: X,
  zap: Zap,
  Zap,
}

export function getIcon(name: string, fallback: LucideIcon = Sparkles): LucideIcon {
  return ICON_MAP[name] ?? ICON_MAP[name.toLowerCase()] ?? fallback
}
